### ISSUE TITLE
Testing Stuff

### ISSUE THREAD

**Issue by willtebbutt** [willtebbutt/GHCNData.jl#2]
@oxinabox

I'm presently using DataDeps to grab data in this package -- it works like a charm, but I'm stumbling a bit when it comes to writing tests. The advice on your docs is that I should set an environment variable to bypass the manually confirmation for data downloads.

Have you seen a GHA that I could use to do this? The standard one generated by PkgTemplates doesn't expose the code that's run, so it's not clear me how this should be done in practice. I took a look at DataDeps' CI action, but it wasn't clear to me from that how to proceed.

**Comment by oxinabox** [comment]
Apparently you do it using `env` as part of your `step`
https://docs.github.com/en/actions/reference/environment-variables

Or you could just set it as an envirment vaiable in julia; during your tests.
`ENV["DATADEPS_ALWAYS_ACCEPT"]="true"`
(esp if you are not too worried about people having data downloade that thye don't want downloaded during testing on local machine)

**Comment by willtebbutt** [comment]
Amazing -- I'll have a play around with this now.

**Comment by willtebbutt** [comment]
Yup, this appears to work nicely. I've added it to the `uses: julia-actions/julia-runtest@v1` in #4 and it appears to be doing the right thing. Thanks for the help!
